### ISSUE TITLE
请开源此项目的 mkn-mr1 分支

### ISSUE THREAD

**Issue by zhanghai** [MoKee/android_kernel_zte_msm8994#1]
Linux 内核以 GPL 为授权许可，而 [Mokee 目前正在分发 NX510J 基于 Android N 的版本](https://download.mokeedev.com/?device=nx510j)，因此请求开放 Android N 对应的内核源代码。

**Comment by martincz** [comment]
您好，正如魔趣开放的其它项目源代码一样，我们非常乐于这样做，在我们力所能及的情况之下。
为了让更多nx510j机油享受到魔趣最新版本的乐趣，维护者将代码托管在我们的服务器上进行日常构建。
但我们需要遵从与维护者的约定，我们没有权限随意处置该项目的源代码。
非常抱歉，还望理解！

**Comment by xingrz** [comment]
看来你找错了地方：https://github.com/MoKee/android_kernel_nubia_msm8994

**Comment by zhanghai** [comment]
是的，打扰了，十分感谢。
